INSERT INTO PUBLIC.COUNSEL_POINT (NAME,STUDY) VALUES ('Leitura exata',1) ;
INSERT INTO PUBLIC.COUNSEL_POINT (NAME,STUDY) VALUES ('Articulação clara',2) ;
INSERT INTO PUBLIC.COUNSEL_POINT (NAME,STUDY) VALUES ('Pronúncia correta',3) ;
INSERT INTO PUBLIC.COUNSEL_POINT (NAME,STUDY) VALUES ('Fluência',4) ;
INSERT INTO PUBLIC.COUNSEL_POINT (NAME,STUDY) VALUES ('Uso correto de pausas',5) ;
INSERT INTO PUBLIC.COUNSEL_POINT (NAME,STUDY) VALUES ('Ênfase segundo o sentido',6) ;
INSERT INTO PUBLIC.COUNSEL_POINT (NAME,STUDY) VALUES ('Ênfase nas ideias principais',7) ;
INSERT INTO PUBLIC.COUNSEL_POINT (NAME,STUDY) VALUES ('Volume apropriado',8) ;
INSERT INTO PUBLIC.COUNSEL_POINT (NAME,STUDY) VALUES ('Modulação', 9) ;
INSERT INTO PUBLIC.COUNSEL_POINT (NAME,STUDY) VALUES ('Entusiasmo', 10) ;

INSERT INTO PUBLIC.ASSIGNMENTKIND (NAME) VALUES ('Leitura da Bíblia') ;
INSERT INTO PUBLIC.ASSIGNMENTKIND (NAME) VALUES ('Primeira conversa') ;
INSERT INTO PUBLIC.ASSIGNMENTKIND (NAME) VALUES ('Primeira revisita') ;
INSERT INTO PUBLIC.ASSIGNMENTKIND (NAME) VALUES ('Segunda revisita') ;
INSERT INTO PUBLIC.ASSIGNMENTKIND (NAME) VALUES ('Terceira revisita') ;
INSERT INTO PUBLIC.ASSIGNMENTKIND (NAME) VALUES ('Estudo bíblico') ;
INSERT INTO PUBLIC.ASSIGNMENTKIND (NAME) VALUES ('Discurso') ;
